global:
  scrape_interval: 6s

scrape_configs:
  - job_name: dev_vagas
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["host.docker.internal:8080"]
        labels:
          application: "dev_vagas"